AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ServiceName:
    Type: String
    Default: sam-sample
  Stage:
    Type: String
    Default: dev

Resources:

  HelloWorldApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${ServiceName}-${Stage}-api
      StageName:
        Ref: Stage

      DefinitionBody:

        openapi: "3.0.1"
        info:
          title: "sample-api"
          version: "v1.0"
        paths:
          /:
            get:
              summary: Says Hello
              description: This is a sample endpoint
              responses:
                '200':
                  description: "OK"
                '500':
                  description: "Internal Server Error"
                  content: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs10.x

      FunctionName:
        Fn::Join:
          - '-'
          - - !Ref ServiceName
            - !Ref Stage
            - 'hello-world'

